language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g bower
  - npm install -g grunt-cli

install:
  - bower install --config.interactive=false
  - npm install

after_script: grunt coveralls
